server:
  port: 8080
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: kurento
#    key-store-type: JKS
#    key-alias: kurento-selfsigned
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_URL}/ikar_data
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
